version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile 
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app  # Mount local backend code into container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/videofx
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    image: node:20  # use Node image to run React
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app  # Mount local frontend code
    ports:
      - "3000:3000"  # React dev server
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Mount the Redis volume
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=videofx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@videofx.app
        PGADMIN_DEFAULT_PASSWORD: password
      ports:
        - "5050:80"
      depends_on:
        - postgres
      networks:
        - app-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge